version: "3.9"
services:
  daemon:
    image: minaprotocol/mina-daemon:1.3.1.2-25388a0-focal-mainnet
    restart: always
    command: >
      daemon
        --block-producer-key /root/keys/blockproducer-key
        --block-producer-password PASSWORD
        --coinbase-receiver B62yourCOINBASEreceiverWALLETaddress
        --uptime-url https://uptime-backend.minaprotocol.com/v1/submit 
        --uptime-submitter-key /root/keys/blockproducer-key
        --insecure-rest-server
        --file-log-level Debug
        --log-level Info
        --open-limited-graphql-port
        --limited-graphql-port 3095
        --peer-list-url https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt
    environment:
      - UPTIME_PRIVKEY_PASS=PASSWORD
    ports:
      - "8302:8302"
    volumes:
      - ./keys:/root/keys
      - ./minadata:/root/.mina-config
